spring.application.name=api-gateway
server.port=0

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.loadbalancer.enabled=true
spring.cloud.loadbalancer.retry.enabled=true
spring.cloud.loadbalancer.retry.retryable-status-codes=500,502,503,504
spring.cloud.loadbalancer.retry.max-retries-on-next-service-instance=100

eureka.client.service-url.defaultZone = http://localhost:5000/eureka


app.jwt-secret=T1Bz1I5L34k6Y8qAZE7d9XJlhxL0UnUQAfJqD/5ZrjY=
app.jwt-expiration=86400000
