spring.application.name=coin-currency-service
app.api-key=73ce4e96c7d79ec01a113214607eca62

eureka.client.service-url.defaultZone = http://localhost:5000/eureka

server.servlet.context-path=/currency-app

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

